path_classifiers:
  library: "externals"
extraction:
  cpp:
    prepare:
      packages:
      - "libsdl2-dev"
      - "qtmultimedia5-dev"
      - "clang-format"
      - "libtbb-dev"
      - "libjack-jackd2-dev"
      - "doxygen"
      - "graphviz"
